In [65]:
# Required Libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix

In [28]:
churnData = pd.read_csv('DATA_Customer-Churn.txt')
churnData

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0     Female              0     Yes         No       1           No   
1       Male              0      No         No      34          Yes   
2       Male              0      No         No       2          Yes   
3       Male              0      No         No      45           No   
4     Female              0      No         No       2          Yes   
...      ...            ...     ...        ...     ...          ...   
7038    Male              0     Yes        Yes      24          Yes   
7039  Female              0     Yes        Yes      72          Yes   
7040  Female              0     Yes        Yes      11           No   
7041    Male              1     Yes         No       4          Yes   
7042    Male              0      No         No      66          Yes   

     OnlineSecurity OnlineBackup DeviceProtection TechSupport StreamingTV  \
0                No          Yes               No          No          No   
1               Yes           No              Yes          No          No   
2               Yes          Yes               No          No          No   
3               Yes           No              Yes         Yes          No   
4                No           No               No          No          No   
...             ...          ...              ...         ...         ...   
7038            Yes           No              Yes         Yes         Yes   
7039             No          Yes              Yes          No         Yes   
7040            Yes           No               No          No          No   
7041             No           No               No          No          No   
7042            Yes           No              Yes         Yes         Yes   

     StreamingMovies        Contract  MonthlyCharges TotalCharges Churn  
0                 No  Month-to-month           29.85        29.85    No  
1                 No        One year           56.95       1889.5    No  
2                 No  Month-to-month           53.85       108.15   Yes  
3                 No        One year           42.30      1840.75    No  
4                 No  Month-to-month           70.70       151.65   Yes  
...              ...             ...             ...          ...   ...  
7038             Yes        One year           84.80       1990.5    No  
7039             Yes        One year          103.20       7362.9    No  
7040              No  Month-to-month           29.60       346.45    No  
7041              No  Month-to-month           74.40        306.6   Yes  
7042             Yes        Two year          105.65       6844.5    No  

[7043 rows x 16 columns]

In [29]:
churnData['TotalCharges'] = pd.to_numeric(churnData['TotalCharges'], errors='coerce')

In [30]:
churnData.fillna(churnData.mean(), inplace=True)

C:\Users\Guillaume CAPELLI\AppData\Local\Temp\ipykernel_21464\383873613.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  churnData.fillna(churnData.mean(), inplace=True)


In [31]:
# Extracting the specified features and target
X = churnData[['tenure', 'SeniorCitizen', 'MonthlyCharges', 'TotalCharges']]
y = churnData['Churn']

# Replace 'Yes' and 'No' with 1 and 0 respectively for target variable
y.replace({"Yes": 1, "No": 0}, inplace=True)

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scaling the features
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [37]:
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression()
logistic_model.fit(X_train, y_train)

LogisticRegression()

In [44]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier()
knn_model.fit(X_train, y_train)

KNeighborsClassifier()

In [45]:
from sklearn.tree import DecisionTreeClassifier
decision_tree_model = DecisionTreeClassifier()
decision_tree_model.fit(X_train, y_train)

DecisionTreeClassifier()

In [46]:
for name, model in zip(names, models):
    y_pred_train = model.predict(X_train)
    y_pred_test = model.predict(X_test)
    
    # Convert predicted labels
    if isinstance(y_pred_train[0], str):
        y_pred_train = [1 if x == "Yes" else 0 for x in y_pred_train]
        y_pred_test = [1 if x == "Yes" else 0 for x in y_pred_test]
    
    print(f"---- {name} ----")
    print(f"Training Accuracy: {accuracy_score(y_train, y_pred_train)}")
    print(f"Test Accuracy: {accuracy_score(y_test, y_pred_test)}")
    print(f"Training Precision: {precision_score(y_train, y_pred_train)}")
    print(f"Test Precision: {precision_score(y_test, y_pred_test)}")
    print(f"Training Recall: {recall_score(y_train, y_pred_train)}")
    print(f"Test Recall: {recall_score(y_test, y_pred_test)}")
    print("\n")

---- Logistic Regression ----
Training Accuracy: 0.7882499112531062
Test Accuracy: 0.8034066713981547
Training Precision: 0.6498516320474778
Test Precision: 0.692
Training Recall: 0.4391711229946524
Test Recall: 0.46380697050938335


---- KNN ----
Training Accuracy: 0.8335108271210507
Test Accuracy: 0.7757274662881476
Training Precision: 0.728688524590164
Test Precision: 0.5916398713826366
Training Recall: 0.5942513368983957
Test Recall: 0.4932975871313673


---- Decision Tree ----
Training Accuracy: 0.9907703230386936
Test Accuracy: 0.7381121362668559
Training Precision: 0.9918256130790191
Test Precision: 0.5052631578947369
Training Recall: 0.9732620320855615
Test Recall: 0.514745308310992




In [47]:
from sklearn.model_selection import cross_val_score

# For logistic regression
lr_scores = cross_val_score(logistic_model, X, y, cv=5)  # Assuming 5 folds
print("Logistic Regression Cross-Val Scores:", lr_scores)
print("Average Logistic Regression Score:", np.mean(lr_scores))

# For KNN
knn_scores = cross_val_score(knn_model, X, y, cv=5)
print("KNN Cross-Val Scores:", knn_scores)
print("Average KNN Score:", np.mean(knn_scores))

# For Decision Tree
dt_scores = cross_val_score(decision_tree_model, X, y, cv=5)
print("Decision Tree Cross-Val Scores:", dt_scores)
print("Average Decision Tree Score:", np.mean(dt_scores))


Logistic Regression Cross-Val Scores: [0.79559972 0.79063165 0.78140525 0.79190341 0.79403409]
Average Logistic Regression Score: 0.790714824343506
KNN Cross-Val Scores: [0.75514549 0.7707594  0.76721079 0.75568182 0.76988636]
Average KNN Score: 0.7637367733402155
Decision Tree Cross-Val Scores: [0.71753016 0.73243435 0.71185238 0.69815341 0.734375  ]
Average Decision Tree Score: 0.7188690601006517


In [48]:
from sklearn.ensemble import RandomForestClassifier

# Initialize the model
rf_model = RandomForestClassifier()

# Train the model
rf_model.fit(X_train, y_train)

# Predict and check the accuracy
rf_pred_train = rf_model.predict(X_train)
rf_pred_test = rf_model.predict(X_test)

print("Random Forest Training Accuracy:", accuracy_score(y_train, rf_pred_train))
print("Random Forest Test Accuracy:", accuracy_score(y_test, rf_pred_test))

Random Forest Training Accuracy: 0.9907703230386936
Random Forest Test Accuracy: 0.7735982966643009


In [49]:
from sklearn.model_selection import GridSearchCV

# Define parameter grid
param_grid = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

grid_search = GridSearchCV(rf_model, param_grid, cv=5, verbose=2, n_jobs=-1)
grid_search.fit(X_train, y_train)

# Print best parameters
print("Best parameters found: ", grid_search.best_params_)

# Retrain the model with best parameters
best_rf = grid_search.best_estimator_


Fitting 5 folds for each of 144 candidates, totalling 720 fits
Best parameters found:  {'max_depth': 10, 'min_samples_leaf': 4, 'min_samples_split': 5, 'n_estimators': 100}


In [50]:
from sklearn.ensemble import RandomForestClassifier

best_params = {'max_depth': 10, 'min_samples_leaf': 4, 'min_samples_split': 5, 'n_estimators': 100}
rf_best = RandomForestClassifier(**best_params)
rf_best.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, min_samples_leaf=4, min_samples_split=5)

In [51]:
y_pred = rf_best.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Random Forest (Tuned) Test Accuracy: {accuracy}")

Random Forest (Tuned) Test Accuracy: 0.8019872249822569


In [72]:
# Original distribution
print("\nOriginal Data Distribution:")
print(y.value_counts())
print()

# Display confusion matrix for Tuned Random Forest
print("\nConfusion Matrix for Original Data:")
print(confusion_matrix(y_test, y_pred))


Original Data Distribution:
0    5174
1    1869
Name: Churn, dtype: int64


Confusion Matrix for Original Data:
[[954  82]
 [197 176]]


In [71]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.utils import resample

X_minority_upsampled = resample(X_minority, replace=True, n_samples=len(X_majority), random_state=42)
y_minority_upsampled = [1] * len(X_majority)
X_upsampled = pd.concat([X_majority, X_minority_upsampled])
y_upsampled = np.concatenate([y[y == 0], y_minority_upsampled])
X_train_upsampled, X_test_upsampled, y_train_upsampled, y_test_upsampled = train_test_split(X_upsampled, y_upsampled, test_size=0.2, random_state=42)
rf_upsampled = RandomForestClassifier()
rf_upsampled.fit(X_train_upsampled, y_train_upsampled)
y_pred_upsampled = rf_upsampled.predict(X_test_upsampled)
accuracy_upsampled = accuracy_score(y_test_upsampled, y_pred_upsampled)
print(f"\nUpsampled Random Forest Accuracy: {accuracy_upsampled:.4f}")
print("\nUpsampled Data Distribution:")
print(pd.Series(y_upsampled).value_counts())
print("\nConfusion Matrix for Upsampled Data:")
print(confusion_matrix(y_test_upsampled, y_pred_upsampled))


Upsampled Random Forest Accuracy: 0.8995

Upsampled Data Distribution:
0    5174
1    5174
dtype: int64

Confusion Matrix for Upsampled Data:
[[876 168]
 [ 40 986]]


In [69]:
X_majority = X[y == 0]
X_minority = X[y == 1]
X_majority_downsampled = resample(X_majority, replace=False, n_samples=len(X_minority), random_state=42)
y_majority_downsampled = [0] * len(X_minority)
X_downsampled = pd.concat([X_minority, X_majority_downsampled])
y_downsampled = np.concatenate([y[y == 1], y_majority_downsampled])
X_train_downsampled, X_test_downsampled, y_train_downsampled, y_test_downsampled = train_test_split(X_downsampled, y_downsampled, test_size=0.2, random_state=42)
rf_downsampled = RandomForestClassifier()
rf_downsampled.fit(X_train_downsampled, y_train_downsampled)
y_pred_downsampled = rf_downsampled.predict(X_test_downsampled)
accuracy_downsampled = accuracy_score(y_test_downsampled, y_pred_downsampled)
print(f"\nDownsampled Random Forest Accuracy: {accuracy_downsampled:.4f}")
print("\nDownsampled Data Distribution:")
print(pd.Series(y_downsampled).value_counts())
print("\nConfusion Matrix for Downsampled Data:")
print(confusion_matrix(y_test_downsampled, y_pred_downsampled))


Downsampled Random Forest Accuracy: 0.7219

Downsampled Data Distribution:
1    1869
0    1869
dtype: int64

Confusion Matrix for Downsampled Data:
[[263 106]
 [102 277]]


In [66]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)
rf_smote = RandomForestClassifier(random_state=42)
rf_smote.fit(X_train_smote, y_train_smote)
y_pred_smote = rf_smote.predict(X_test)
accuracy_smote = accuracy_score(y_test, y_pred_smote)
print(f"\nSMOTE Random Forest Accuracy: {accuracy_smote:.4f}")
print("\nSMOTE Data Distribution:")
print(pd.Series(y_train_smote).value_counts())
print("\nConfusion Matrix for SMOTE Data:")
print(confusion_matrix(y_test, y_pred_smote))


SMOTE Random Forest Accuracy: 0.7303

SMOTE Data Distribution:
0    4138
1    4138
Name: Churn, dtype: int64

Confusion Matrix for SMOTE Data:
[[793 243]
 [137 236]]
